Feature/entry count featuredrift
the-deep-nlp/core-server pull request #7
Opened 2023-03-14 04:39 UTC by Rup-Narayan-Rajbanshi

## Changes
  - Add entry count in feature drift.

2023-03-14 05:57 UTC, Rup-Narayan-Rajbanshi commented
@ranjan-stha , @bewakes I have mentioned the pr to be draft. errors will be fixed soon.

2023-03-14 09:33 UTC, thenav56 approved these changes

2023-03-14 09:50 UTC, ranjan-stha requested changes

2023-03-14 09:50 UTC, ranjan-stha commented on core/tasks/model_monitoring.py
>          )
@Rup-Narayan-Rajbanshi Why only 10 samples ? We need to pass all the samples collected over a period of time (e.g. week or daily -> depends upon when the task is scheduled).

2023-03-15 04:11 UTC, ranjan-stha requested changes

2023-03-15 04:11 UTC, ranjan-stha commented on core/tasks/model_monitoring.py
>          )
use like this: feature_drift.comptue_feature_drift(len(reference_data_df), len(current_data_df))

2023-03-15 04:42 UTC, bewakes commented on core/models.py
> +    entry_count = models.PositiveIntegerField(blank=True, null=True)
Maybe have `default=0` instead of nullable?

2023-03-17 08:04 UTC, bewakes requested changes

2023-03-17 08:04 UTC, bewakes commented on core/tasks/model_monitoring.py
> +        entry_ids = [record['entry_id'] for record in df.to_dict("records")]
Calling `df.to_dict("records")` is redundant here. More importantly, it costs extra computation to convert to dict. The same effect can be achieved by something like `entry_ids = list(df.entry_id)` without the need of extra conversion.

2023-03-17 08:04 UTC, bewakes commented on core/tasks/model_monitoring.py
>          )
I think we can have query for `newly_added_entries` defined simply as following, because classification prediction has entry as one to one field:
```python
newly_added_entries = Entry.objects.filter(classificationpredictions__isnull=True)
```
I noticed it in this PR but the current definition is not efficient.

2023-03-17 08:04 UTC, bewakes commented on core/tasks/model_monitoring.py
> +        entry_project_id_dict = {
If in the `newly_added_entries` you prefetch `lead__project` then you can simply do
```python
entry_project_id_dict = {
      entry.original_entry_id: entry.lead.project.original_project_id 
      for entry in newly_added_entries
}
```
Or something like that.
Fetching projects that way doesn't just seem very good.

2023-03-17 10:24 UTC, bewakes approved these changes

2023-03-20 06:45 UTC, ranjan-stha approved these changes

2023-03-20 07:54 UTC, merged